iven(/^I have the username$/) do                                                                                                                                                                                                             
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I have the proper password$/) do                                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
When(/^I type them in to the boxes$/) do                                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end   

When(/^I click the login button$/) do                                                                                                                                                                                                         
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should be allowed to the homepage$/) do                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I have the wrong username and password$/) do                                                                                                                                                                                          
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
When(/^I enter them into the boxes$/) do                                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should get an error stating my username or password was incorrect$/) do                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I must try again before proceeding$/) do                                                                                                                                                                                               
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I am not logged in$/) do                                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
When(/^I enter my username$/) do                                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I enter my password$/) do                                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the website should take me to the home page$/) do                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I enter the correct credentials$/) do                                                                                                                                                                                                 
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I am currently logged in$/) do                                                                                                                                                                                                         
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should be on the homepage$/) do                                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end

Given(/^I have entered incorrect username$/) do                                                                                                                                                                                               
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I have entered an incorrect password$/) do                                                                                                                                                                                            
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end   

Then(/^the login page should show an error$/) do                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I have the proper key for the door$/) do                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end    

When(/^I insert key into slot$/) do                                                                                                                                                                                                           
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
When(/^I turn the key to the right$/) do                                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end     

Then(/^the door should be successfully unlocked$/) do                                                                                                                                                                                         
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^the homeowner does not have the proper key$/) do                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end   

When(/^user attempts to unlock door$/) do                                                                                                                                                                                                     
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the door won’t unlock$/) do                                                                                                                                                                                                            
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end  

Then(/^user must call his angry wife$/) do                                                                                                                                                                                                    
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^the user has unlocked the door$/) do                                                                                                                                                                                                  
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end      

When(/^the knob is turned$/) do                                                                                                                                                                                                               
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the door should be able to open$/) do                                                                                                                                                                                                  
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           

Then(/^the owner is allowed inside$/) do                                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^the user has not unlocked the door$/) do                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end

Then(/^the door stays shut$/) do                                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the owner is left outside$/) do                                                                                                                                                                                                        
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end 