Given(/^I am not logged in$/) do                                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
When(/^I enter my username$/) do                                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I enter my password$/) do                                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end     

Then(/^the website should take me to the home page$/) do                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I am an authenticated user$/) do                                                                                                                                                                                                       
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I enter the correct credentials$/) do                                                                                                                                                                                                 
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I am currently logged in$/) do                                                                                                                                                                                                         
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should be on the homepage$/) do                                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I have entered incorrect username$/) do                                                                                                                                                                                               
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I have entered an incorrect password$/) do                                                                                                                                                                                            
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the login page should show an error$/) do                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I am not an authenticated user$/) do                                                                                                                                                                                                   
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end 