Given(/^I have nothing in my cart$/) do                                                                                                                                                                                                       
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I go to cart page$/) do                                                                                                                                                                                                               
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the page should show an empty cart$/) do                                                                                                                                                                                               
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I added items to the cart$/) do                                                                                                                                                                                                       
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I go to the cart page$/) do                                                                                                                                                                                                           
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the page should show my items in the cart$/) do                                                                                                                                                                                        
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end  

Given(/^I have an item in my cart$/) do                                                                                                                                                                                                       
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I click the increase quantity button$/) do                                                                                                                                                                                            
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the quantity of the item should increase$/) do                                                                                                                                                                                         
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the total price should increase$/) do                                                                                                                                                                                                  
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I click the decrease quantity button$/) do                                                                                                                                                                                            
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the quantity of the item should decrease$/) do                                                                                                                                                                                         
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the total price should decrease$/) do                                                                                                                                                                                                  
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I click the delete item button$/) do                                                                                                                                                                                                  
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the item should be removed$/) do                                                                                                                                                                                                       
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I click the Checkout button$/) do                                                                                                                                                                                                     
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should be sent to the checkout page$/) do                                                                                                                                                                                            
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I have no items in my cart$/) do                                                                                                                                                                                                      
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I click the checkout button$/) do                                                                                                                                                                                                     
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the page should stay on the cart page$/) do                                                                                                                                                                                            
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should be told cart is empty$/) do                                                                                                                                                                                                   
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                         