Given(/^I am on the checkout page$/) do                                                                                                                                                                                                       
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I have a total greater than zero$/) do                                                                                                                                                                                                
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I enter my information correctly$/) do                                                                                                                                                                                                
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should see a successful checkout page$/) do                                                                                                                                                                                          
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the transaction should be processed$/) do                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I enter my information incorrectly$/) do                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should see an error message$/) do                                                                                                                                                                                                    
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^The transaction will not be processed$/) do                                                                                                                                                                                            
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end  