iven(/^I have come from the checkout page$/) do                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I enter my credit card information correctly$/) do                                                                                                                                                                                    
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the payment should be processed$/) do                                                                                                                                                                                                  
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should be sent to an order summary page$/) do                                                                                                                                                                                        
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I enter my credit card information incorrectly$/) do                                                                                                                                                                                  
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the payment should not be processed$/) do                                                                                                                                                                                              
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should stay on the payment page$/) do                                                                                                                                                                                                
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should see an error$/) do                                                                                                                                                                                                            
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I click the cancel button$/) do                                                                                                                                                                                                       
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should be sent back to the checkout page$/) do                                                                                                                                                                                       
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end  