Given(/^I am on the Catalog page$/) do                                                                                                                                                                                                        
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I click the show cart buton$/) do                                                                                                                                                                                                     
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^I should be taken to the cart page$/) do                                                                                                                                                                                               
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I am on the catalog page$/) do                                                                                                                                                                                                        
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^I select an item$/) do                                                                                                                                                                                                                
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the item should be added to the cart$/) do                                                                                                                                                                                             
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                    