Given(/^a cell is alive$/) do                                                                                                                                                                                                                 
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^has two or three alive neighbors$/) do                                                                                                                                                                                                
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the cell lives on$/) do                                                                                                                                                                                                                
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^cell has less than two neighbors$/) do                                                                                                                                                                                                
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the cell dies$/) do                                                                                                                                                                                                                    
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^a cell is dead$/) do                                                                                                                                                                                                                  
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^cell has three live neighbors$/) do                                                                                                                                                                                                   
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the cell becomes alive$/) do                                                                                                                                                                                                           
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^the cell has more than three neighbors$/) do                                                                                                                                                                                          
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end  